export const REDIRECT_HANDLER_ACCOUNT = 'REDIRECT_HANDLER_ACCOUNT';
export const LOADING_HANDLER_ACCOUNT = 'LOADING_HANDLER_ACCOUNT';
export const SUBMIT_EMAIL = 'SUBMIT_EMAIL';
export const SUBMIT_EMAIL_START = 'SUBMIT_EMAIL_START';
export const SUBMIT_EMAIL_SUCCESS = 'SUBMIT_EMAIL_SUCCESS';
export const SUBMIT_EMAIL_FAIL = 'SUBMIT_EMAIL_FAIL';
export const SUBMIT_ERROR_ACCOUNT = 'SUBMIT_ERROR_ACCOUNT';
export const ERROR_HANDLER_ACCOUNT = 'ERROR_HANDLER_ACCOUNT';
export const CANCEL_HANDLER_ACCOUNT = 'CANCEL_HANDLER_ACCOUNT';

export const REDIRECT_HANDLER_SIGNUP = 'REDIRECT_HANDLER_SIGNUP';
export const LOADING_HANDLER_SIGNUP = 'LOADING_HANDLER_SIGNUP';
export const SUBMIT_SIGNUP = 'SUBMIT_SIGNUP';
export const SUBMIT_SIGNUP_START = 'SUBMIT_SIGNUP_START';
export const SUBMIT_SIGNUP_SUCCESS = 'SUBMIT_SIGNUP_SUCCESS';
export const SUBMIT_SIGNUP_FAIL = 'SUBMIT_SIGNUP_FAIL';
export const SUBMIT_ERROR_SIGNUP = 'SUBMIT_ERROR_SIGNUP';
export const ERROR_HANDLER_SIGNUP = 'ERROR_HANDLER_SIGNUP';
export const CANCEL_HANDLER_SIGNUP = 'CANCEL_HANDLER_SIGNUP';

export const REDIRECT_HANDLER_LOGIN = 'REDIRECT_HANDLER_LOGIN';
export const LOADING_HANDLER_LOGIN = 'LOADING_HANDLER_LOGIN';
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const SUBMIT_LOGIN_START = 'SUBMIT_LOGIN_START';
export const SUBMIT_LOGIN_SUCCESS = 'SUBMIT_LOGIN_SUCCESS';
export const SUBMIT_LOGIN_FAIL = 'SUBMIT_LOGIN_FAIL';
export const SUBMIT_ERROR_LOGIN = 'SUBMIT_ERROR_LOGIN';
export const ERROR_HANDLER_LOGIN = 'ERROR_HANDLER_LOGIN';
export const CANCEL_HANDLER_LOGIN = 'CANCEL_HANDLER_LOGIN';

export const REDIRECT_HANDLER_FORGOT = 'REDIRECT_HANDLER_FORGOT';
export const REDIRECT_INFO = 'REDIRECT_INFO';
export const LOADING_HANDLER_FORGOT = 'LOADING_HANDLER_FORGOT';
export const SUBMIT_FORGOT = 'SUBMIT_FORGOT';
export const SUBMIT_FORGOT_START = 'SUBMIT_FORGOT_START';
export const SUBMIT_FORGOT_SUCCESS = 'SUBMIT_FORGOT_SUCCESS';
export const SUBMIT_FORGOT_FAIL = 'SUBMIT_FORGOT_FAIL';
export const SUBMIT_ERROR_FORGOT = 'SUBMIT_ERROR_FORGOT';
export const ERROR_HANDLER_FORGOT = 'ERROR_HANDLER_FORGOT';
export const CANCEL_HANDLER_FORGOT = 'CANCEL_HANDLER_FORGOT';

export const REDIRECT_HANDLER_RESET = 'REDIRECT_HANDLER_RESET';
export const LOADING_HANDLER_RESET = 'LOADING_HANDLER_RESET';
export const SUBMIT_RESET = 'SUBMIT_RESET';
export const SUBMIT_RESET_START = 'SUBMIT_RESET_START';
export const SUBMIT_RESET_SUCCESS = 'SUBMIT_RESET_SUCCESS';
export const SUBMIT_RESET_FAIL = 'SUBMIT_RESET_FAIL';
export const SUBMIT_ERROR_RESET = 'SUBMIT_ERROR_RESET';
export const ERROR_HANDLER_RESET = 'ERROR_HANDLER_RESET';
export const CANCEL_HANDLER_RESET = 'CANCEL_HANDLER_RESET';

export const LOADING_HANDLER_LIBRARY = 'LOADING_HANDLER_LIBRARY';
export const SUBMIT_ADD = 'SUBMIT_ADD';
export const SUBMIT_ADD_START = 'SUBMIT_ADD_START';
export const SUBMIT_ADD_SUCCESS = 'SUBMIT_ADD_SUCCESS';
export const SUBMIT_ADD_FAIL = 'SUBMIT_ADD_FAIL';
export const ERROR_HANDLER_LIBRARY = 'ERROR_HANDLER_LIBRARY';
export const SIGNOUT_HANDLER = 'SIGNOUT_HANDLER';

export const LOADING_HANDLER_PROFILE = 'LOADING_HANDLER_PROFILE';
export const SUBMIT_DELETE = 'SUBMIT_DELETE';
export const SUBMIT_DELETE_START = 'SUBMIT_DELETE_START';
export const SUBMIT_DELETE_SUCCESS = 'SUBMIT_DELETE_SUCCESS';
export const SUBMIT_DELETE_FAIL = 'SUBMIT_DELETE_FAIL';
export const ERROR_HANDLER_PROFILE = 'ERROR_HANDLER_PROFILE';